name: Metrics
on:
  # Schedule 30-minute updates
  schedule: [{cron: '*/15 * * * *'}]
  # (optional) Run workflow manually
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: tannerhawkins/metrics@master
        with:
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: classic
          plugin_habits_from: 10000
          plugin_habits_days: 1000
          config_timezone: America/New_York
          token: ${{ secrets.METRICS_TOKEN }}
