name: Metrics
on:
  # Schedule 30-minute updates
  schedule: [{cron: '*/15 * * * *'}]
  # (optional) Run workflow manually
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: graph
          plugin_habits_from: 1000
          plugin_habits_languages_threshold: 5%
          config_timezone: America/New_York
          token: ${{ secrets.METRICS_TOKEN }}
